FROM node:21.5.0

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

# removing src folder after building
RUN rm -rf ./src

# port no in main.ts
EXPOSE 3000

# Copy entrypoint script
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# Run the entrypoint script
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]